POST http://localhost:8000/carousels 
Content-Type: application/json

{
    "title": "test2",
    "description": "Loreum ipsum",
    "link": "http://www.test.fr",
    "picture": "test"
}

###
GET http://localhost:8000/carousels


###
PUT http://localhost:8000/carousels/52da6422-1c9c-46e1-9685-ec7ca433d834 
Content-Type: application/json

{
    "title": "Toto",
}