POST http://localhost:8000/carousels/
Content-Type: application/json

{
    "title": "image 1",
    "description": "description 1",
    "link": "http://www.test1.fr",
    "picture": "uneimage.jpg"    
}

###
GET http://localhost:8000/carousels/

###

GET http://localhost:8000/carousels/0dadbb85-1f33-4ea3-8309-8a93c979264d




###
PUT http://localhost:8000/carousels/0dadbb85-1f33-4ea3-8309-8a93c979264d
Content-Type: application/json

{
    "title": "modified img",
    "description": "Loreum ipsum",
    "link": "http://www.modifyme.fr",
    "picture": "imgmodified.jpg"    
}