GET http://localhost:8000/carousels/


###

POST http://localhost:8000/carousels 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlZjUxMjc5LWQ4MzktNDIwOS1hZDFhLTFkMTNjNTZiMmMxNSIsImVtYWlsIjoiYW50aG9uaW42NEBsb29rdXAuZnIiLCJpYXQiOjE1OTM2MDEzMjMsImV4cCI6MTU5MzYwNDkyM30.tWOFDSZw_cknYtcWQA1pCtbdCBMJsZ1l0G2Jlod5bBg

{
    "title": "Hello3",
    "description": "je suis une image",
    "link": "http://postme.jpg",
    "picture": "postpic.jpg"
}

###


POST http://localhost:8000/carousels 
Content-Type: application/json

{
    "titl": "Hello3"
}


###

GET http://localhost:8000/carousels/b0f4005b-05bd-4e0e-9f2d-31e843329c6c




###
PUT http://localhost:8000/carousels/3a6a2366-8ab4-47aa-a6a2-746443fff6b4
Content-Type: application/json

{
    "title": "Salut JeanMich",
    "description": "Loreum ipsum indolor",
    "link": "http://www.test.fr",
    "picture": "test"    
}

###
DELETE http://localhost:8000/carousels/3a6a2366-8ab4-47aa-a6a2-746443fff6b4
