GET http://localhost:8000/admin/09abcb57-4076-47fa-95dd-78ce3be653a4


###

POST  http://localhost:8000/admin
Content-Type: application/json

{
    "email": "anthonin64@lookup.fr",
    "password": "toto"
    
}

###

POST http://localhost:8000/admin/login
Content-Type: application/json


{
    "email": "anthonin64@lookup.fr",
    "password": "toto"
}



####

PUT http://localhost:8000/admin/login/09abcb57-4076-47fa-95dd-78ce3be653a4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA5YWJjYjU3LTQwNzYtNDdmYS05NWRkLTc4Y2UzYmU2NTNhNCIsImVtYWlsIjoiYW50aG9uaW42NEBsb29rdXAuZnIiLCJpYXQiOjE1OTQzMjY2MzAsImV4cCI6MTU5NDMzMDIzMH0.VClbSACwAuXNUrl4z-ukcjnP9RfrTUiXq5elJ5uPN20


{
    "companyName": "LookUp",
    "streetName": "rue des cerisiers",
    "streetNumber": 12,
    "postalCode": 40200,
    "city": "Tarnos",
    "phone": 666666666,
    "siret": "12345678901234",
    "email": "anthonin@lookup.fr",
    "password": "toto64"
}