GET http://localhost:8000/admin/53afb808-1aa6-49e2-8cef-264d9118467e


###

POST  http://localhost:8000/admin
Content-Type: application/json
X-Http-Method-Override: MERGE

{
    "email": "anthonin@lookup.fr",
    "password": "toto"
    
}

###

PUT http://localhost:8000/admin/53afb808-1aa6-49e2-8cef-264d9118467e
Content-Type: application/json

{
    "companyName": "LookUp",
    "streetName": "rue des cerisiers",
    "streetNumber": 12,
    "postalCode": 40200,
    "city": "Tarnos",
    "phone": 666666666,
    "siret": "12345678901234"
}