GET http://localhost:8000/products

###

GET http://localhost:8000/products/1b1e794f-0293-4603-84b7-0fc0477c89d2

###

POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "support man",
    "price": 22200002.5,
    "description": "ceci est un support de mamie",
    "picture": "iamzepicture.jpg"
}