GET http://localhost:8000/products

###

GET http://localhost:8000/products/30273232-15d3-488c-8446-d1798cb68faa

###

POST http://localhost:8000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzODEzOGIzLTgxMmUtNGVkMC04MmQ1LWNkZTQ4MTU0YTU4MyIsImVtYWlsIjoiYW50b25pbkBsb29rdXAuZnIiLCJpYXQiOjE1OTQ4MjA0NjAsImV4cCI6MTU5NDgyNDA2MH0.p2zvyYncnCQ8HncT5WAhQ7H1US3G3Z_ibeeLE9IZ3Rc

{
    "name": "support man",
    "price": 22200002.5,
    "description": "ceci est un support de mamie",
    "picture": "iamzepicture.jpg"
}

###

GET http://localhost:8000/products/897502ba-a03a-4cdf-b629-0442f0fcd9dd/products_info




###
PUT http://localhost:8000/products/acacdeba-1f26-45ed-bc7b-893c3938a5ac
Content-Type: application/json

{
    "name": "support man 3000",
    "price": 22200002.5,
    "description": "ceci est un support de mamie",
    "picture": "iamzepicture.jpg"
}


###
DELETE http://localhost:8000/products/3a472c64-0115-4da9-92ee-7b037e356a3f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzODEzOGIzLTgxMmUtNGVkMC04MmQ1LWNkZTQ4MTU0YTU4MyIsImVtYWlsIjoiYW50b25pbkBsb29rdXAuZnIiLCJpYXQiOjE1OTQ4MjA0NjAsImV4cCI6MTU5NDgyNDA2MH0.p2zvyYncnCQ8HncT5WAhQ7H1US3G3Z_ibeeLE9IZ3Rc