####
GET http://localhost:8000/products_info

###
POST http://localhost:8000/products_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzODEzOGIzLTgxMmUtNGVkMC04MmQ1LWNkZTQ4MTU0YTU4MyIsImVtYWlsIjoiYW50b25pbkBsb29rdXAuZnIiLCJpYXQiOjE1OTQ4MjA0NjAsImV4cCI6MTU5NDgyNDA2MH0.p2zvyYncnCQ8HncT5WAhQ7H1US3G3Z_ibeeLE9IZ3Rc

{
  "title": "Hello",
  "description": "Lorem ipsum",
  "description2": "Lorem ipsum",
  "description3": "Lorem ipsum",
  "picture":"star.jpg",
  "picture2":"star2.jpg",
  "picture3":"star3.jpg",
  "ProductUuid": "0f6f83e1-34da-4bd2-9f8d-c6288319d8c2"
}

###
PUT http://localhost:8000/products_info/bbd20e24-964d-4e3c-a21e-217cdd62d96f
Content-Type: application/json

{
    "title":"Bravo"
}