POST http://localhost:8000/sendMail
Content-Type: application/json

{
    "emailFrom":"ryo_69@hotmail.fr",
    "emailTo":"ryo_69@hotmail.fr",
    "subject":"Hello Everybody",
    "message":"BlaBlabla ",
    "html":"<b>BlaBlabla</b>"
}