###
POST http://localhost:8000/services
Content-Type: application/json
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5Y2RlNGMxLTI0Y2QtNDlhMC1hNTQ2LWE5YjhlNmMzNmE5YiIsImVtYWlsIjoiYW50aG9uaW42NEBsb29rdXAuZnIiLCJpYXQiOjE1OTM3MjEyMTcsImV4cCI6MTU5MzcyNDgxN30.MyL3HLltrtvBKn5vwv13LQbQZoiR01kcWo2OfJ_485w

{
    "title": "hello",
    "description": "blabla",
    "logo": "htpp://www.test.fr/logo.jpg"
}